# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
defaults:
      run:
        working-directory: web/adbooksweb-app
jobs:

  job1:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: adaptedbooksdb
      DB_USER: root
      DB_PASSWORD: root
    steps:
     - uses: actions/checkout@v2.1.0
     - run: |
          sudo /etc/init.d/mysql start
  job2:
    runs-on: ubuntu-latest
    needs: job1
    defaults:
          run:
            working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: mvn spring-boot:run
        
  job3:

    runs-on: ubuntu-latest
    needs: job2
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm start & npx wait-on http://localhost:3000
    - run: npm test
    - run: npx cucumber-js
    
    - name: Success notification
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: AdaptedBooks-EIS
        DISCORD_AVATAR: https://www.iconsdb.com/icons/preview/green/github-9-xxl.png
      uses: Ilshidur/action-discord@master
      with:
        title: ':green_circle: Entrega existosa'
        color: 3258062
        includeCommits: true
        args: ':green_circle: El push fue exitoso! ${{ github.actor }}: ${{ github.event.head_commit.message }}'
        
        
    - name: Success notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: AdaptedBooks-EIS
        DISCORD_AVATAR: https://www.iconsdb.com/icons/preview/red/github-10-xxl.png
      uses: Ilshidur/action-discord@master
      with:
        title: ':red_circle: Entrega fallida'
        color: 3258062
        includeCommits: true
        args: ':red_circle: Hubo un error con el push ${{ github.actor }}: ${{ github.event.head_commit.message}}'
